# Docker with nginx running vue
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  app: 'chriskilinc-vue'
  imageName: '$(app):$(build.buildId)'

steps:
- script: docker build -t $(imageName) .
  displayName: 'docker build  $(imageName)'

- script: docker tag $(imageName) $(containerRegistryEndpoint)/$(imageName)
  displayName: 'docker tag'

- task: Docker@2
  displayName: 'docker login'
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

- script: docker push $(containerRegistryEndpoint)/$(imageName)
  displayName: 'docker push'

- script: docker rmi $(imageName)
  displayName: 'docker remove image $(imageName)'

- script: docker images
  displayName: 'docker images'